/**
 * This object is generated by the backend in
 * reponse to a service execution.
 * 
 * Attributes:
 * serviceUuid - service uuid that was executed
 * username - username of the user that requested the execution
 * usedParameters - list of the parameters passed to the service
 * response - result of the service execution
 * remainingBalance - number of credits/points remaining in user's account
 * executionDate - time in millis when the service was executed
 */
export class ServiceResponse {
    constructor(public serviceUuid:string = '', 
    public username:string='', public usedParameters:string ='',
    public response:string='', public remainigBalance:number = 0,
    public executionDate:number = 0){}
}
